# CI de Nível 03 - Disparo automático sempre que outro for concluído, como deploy

# Nome que vai aparecer nas opções de pipe
name: 'Execução por Deploy'

# Regras de disparo da execução (Triggers/Gatilhos)
# Gatilho de execução outro workflow = workflow_run


on:
   workflow_run:    
    workflows: ['Execução Manual']
    types:
        - completed



jobs: 

    # Descrição do Job
    e2e-tests:

        # Máquina que o job vai executar
        runs-on: ['ubuntu-latest']

        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        # Passo-a-passo das ações do job
        steps:

            - uses: actions/checkout@v4

            # - uses: actions/setup-node@v4
            #     with:
            #         node-version: lts/*

            - name: Instalando Yarn
              run: npm install -g yarn

            - name: Instalando dependências
              run: yarn

            - name: Instalando Playwright
              run: yarn playwright install
              
            - name: Testes E2E
              run: yarn run e2e


            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: relatorio-de-testes
                  path: ./playwright-report
